# Generated by Django 2.0 on 2017-12-30 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='other', max_length=50)),
                ('date', models.DateTimeField()),
                ('credit_amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('debit_amount', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
